name: Prod Cluster Main
on:
#  schedule:
#    - cron: '0 0 * * 0'  # At 00:00 every Sunday
  push:
    branches:
      - 'main'
    paths:
      - 'modules/digital_ocean_k8s_cluster/**'
      - 'envs/prod_cluster/**'
jobs:
  Prod-Cluster-Apply:
    uses: GDef-Solutions/gdef-infra/.github/workflows/terraform-main.yml@main
    with:
      working_directory: envs/prod_cluster
    secrets:
      TF_VAR_do_token: ${{ secrets.TF_VAR_do_token }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
