name: Prod Cluster PR
on:
  pull_request:
    paths:
      - 'modules/digital_ocean_k8s_cluster/**'
      - 'envs/prod_cluster/**'
jobs:
  Prod-Cluster-Test:
    uses: GDef-Solutions/gdef-infra/.github/workflows/terraform-pr.yml@main
    with:
      working_directory: envs/prod_cluster
    secrets:
      TF_VAR_do_token: ${{ secrets.TF_VAR_do_token }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
